version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: php:7.1.23-cli-stretch
    steps:
      - checkout
      -
        run:
          name: OSの初期設定
          command: |
            apt update && apt -y install python3-dev
            curl "https://bootstrap.pypa.io/get-pip.py" | tac | python
            pip install awscli
      -
        run:
          name: publishスクリプトを取得
          command: |
            aws s3 cp s3://gs2-repos/python/publish/${PUBLISH_VERSION}/publish-${PUBLISH_VERSION}.tar.gz ~/ && tar -zxvf ~/publish-${PUBLISH_VERSION}.tar.gz -C ~/
      -
        run:
          command: |
            bash ~/publish-${PUBLISH_VERSION}/php/publish_packagist.sh ~/publish-${PUBLISH_VERSION}/