version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: php:7.1.23-cli-stretch
    steps:
      - checkout
      -
        run:
          name: OSの初期設定
          command: |
            apt update && apt -y install jq git
      -
        run:
          command: |
            mkdir ~/.ssh
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            export PRODUCT_VERSION=`cat composer.json | jq -r ".version"`
            git push origin :${PRODUCT_VERSION}
            set +e
            git tag -d ${PRODUCT_VERSION}
            set -e
            git tag ${PRODUCT_VERSION}
            git push origin ${PRODUCT_VERSION}
